server:
  port: 8010

mybatis:
  mapper-locations: classpath:mapping/*.xml

# 配置数据源
spring:
  datasource:
    name: all-in-search
    url: jdbc:mysql://127.0.0.1:3306/all-in-search?useSSL=false
    username: root
    password: 123456Aa
    # 使用druid做连接池管理
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
  web:
    resources:
      # true 表示如果所有的controller都没有命中，则使用默认的静态资源处理器做匹配
      add-mappings: true
  mvc:
    throw-exception-if-no-handler-found: true
    # 接入前端静态资源页面
    static-path-pattern: /static/**
  # thymeleaf相关的配置
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html

admin:
  email: admin@shenzui5233.com
  encryptPassword: 4QrcOUm6Wau+VuBX8g+IPg==